resources:
- name: source-code
  type: git
  source:
    uri: git@github.com:flangewad/gs-serving-web-content.git
    branch: master
    private_key: {{private-key}}
- name: pws
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: kmoulang@pivotal.io
    password: {{cf-password}}
    organization: pivotallabs
    space: Beach-London
    skip_cert_check: false

jobs:
- name: some-code-alert
  plan:
  - get: source-code
    trigger: true
  - task: announce-code
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: java
          tag: '8'
      inputs:
      - name: source-code
      outputs:
      - name: package
      run:
        path: source-code/complete/build.sh
  - put: pws
    params:
      manifest: package/manifest.yml

