resources:
- name: source-code
  type: git
  source:
    uri: git@github.com:flangewad/gs-serving-web-content.git
    branch: master
    private_key: {{private-key}}

jobs:
- name: some-code-alert
  plan:
  - get: source-code
    trigger: true
  - task: announce-code
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: java
          tag: '8'
      inputs:
      - name: source-code
      run:
        path: source-code/complete/build.sh

