resource_types:
- name: http-api
  type: docker-image
  source: {repository: aequitas/http-api-resource}

resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/flangewad/gs-serving-web-content
    branch: master
- name: ifttt-rosie
  type: http-api
  source:
      uri: https://maker.ifttt.com/trigger/build_failed/with/key/EPy2lKjIbdn1KUVI69n7S
      method: POST
- name: ifttt-katie
  type: http-api
  source:
    uri: https://maker.ifttt.com/trigger/build_failed/with/key/EPy2lKjIbdn1KUVI69n7S
    method: POST
      # json:
      #     color: "{color}"
      #     message: "Build {BUILD_PIPELINE_NAME}{BUILD_JOB_NAME}, nr: {BUILD_NAME} {message}!"
    # private_key: {{private-key}}
    # private_key: fred
# - name: pws
#   type: cf
#   source:
#     api: {{cf-api}}
#     username: {{cf-username}}
#     password: {{cf-password}}
#     organization: {{cf-organization}}
#     space: {{cf-space}}
#     skip_cert_check: false

jobs:
- name: some-code-alert
  plan:
  - get: source-code
    trigger: true
  # - task: announce-code
  #   config:
  #     platform: linux
  #     image_resource:
  #       type: docker-image
  #       source:
  #         repository: java
  #         tag: '8'
  #     inputs:
  #     - name: source-code
  #     outputs:
  #     - name: package
  #     run:
  #       path: source-code/complete/build.sh
  - task: annouce-build-started
    config:
      platform: linux
      image:  docker:///busybox
      run:
        # path: curl
        # args: [-X, POST https://maker.ifttt.com/trigger/build_failed/with/key/klEoT6Z2YZrtkTLWqvugY]
        path: exit
        args: [1]
    on_failure:
      aggregate:
        - task: annouce-build-failed
          config:
            inputs:
            - name: source-code
            platform: linux
            image:  docker:///switchback/git-debian
            run:
              path: source-code/complete/find_culprit.sh
            outputs:
                - name: culprits
        # - put: ifttt-rosie
      # path: echo
        # args: [Build finished]
  # - put: pws
  #   params:
  #     manifest: package/manifest.yml
